apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ride-connect-ingress
  namespace: ride-connect

spec:
  ingressClassName: nginx

  rules:
  - host: rideconnect.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ride-connect-service
            port:
              number: 8080