apiVersion: v1
kind: Service
metadata:
  name: ride-connect-service
  namespace: ride-connect
spec:
  selector:
    app: ride-connect
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP
