{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ride-connect.serviceAccountName" . }}
  labels:
    {{- include "ride-connect.labels" . | nindent 4 }}
{{- end }}
